import React, { createContext, useContext, useMemo, useState } from 'react';

export const languages = [
  { code: 'en', name: 'English' },
  { code: 'zh', name: 'Chinese (Simplified)' },
  { code: 'es', name: 'Spanish' },
  { code: 'ar', name: 'Arabic' },
  { code: 'hi', name: 'Hindi' },
  { code: 'fr', name: 'French' },
  { code: 'ru', name: 'Russian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'bn', name: 'Bengali' },
  { code: 'id', name: 'Indonesian' },
  { code: 'tr', name: 'Turkish' },
  { code: 'de', name: 'German' },
  { code: 'ja', name: 'Japanese' },
] as const;

export type LanguageCode = (typeof languages)[number]['code'];

const english = {
  common_back: '< Back',
  common_active: 'Active',
  common_light: 'Light',
  common_dark: 'Dark',
  common_system: 'System',
  common_unable_open: 'Unable to open',
  common_link_unsupported: 'This link is not supported on your device.',
  common_something_wrong: 'Something went wrong',
  common_try_again: 'Please try again.',
  common_close: 'Close',
  tabs_home: 'Home',
  tabs_prayer_time: 'Prayer Time',
  tabs_quran: 'Quran',
  tabs_info: 'Info',
  info_kicker: 'MYGNI SUPPORT',
  info_title: 'Info & Settings',
  info_subtitle:
    'Manage app details, policy pages, quick actions, theme mode, and language.',
  info_theme: 'Theme',
  info_color_theme: 'Color Theme',
  info_color_theme_hint: 'Choose your preferred accent color',
  menu_takti: 'Takti',
  info_language: 'Language',
  info_language_hint: 'Change app language for supported screens.',
  info_choose_language: 'Choose Language',
  info_about_title: 'About Us',
  info_about_subtitle: 'Know the mission and app details',
  info_contact_title: 'Contact Us',
  info_contact_subtitle: 'Reach support for help and feedback',
  info_privacy_title: 'Privacy Policy',
  info_privacy_subtitle: 'Understand your data and privacy',
  info_terms_title: 'Terms & Conditions',
  info_terms_subtitle: 'Read usage terms and guidelines',
  info_share_title: 'Share App',
  info_share_subtitle: 'Invite friends and family',
  info_more_apps_title: 'More Apps',
  info_more_apps_subtitle: 'See other apps from our team',
  info_rate_title: 'Rate This App',
  info_rate_subtitle: 'Support us with your rating',
  info_coming_soon: 'This section will be available soon.',
  info_share_failed: 'Share failed',
  info_share_failed_subtitle: 'Unable to share app right now.',
  info_share_message:
    'Check out MyGNI app for prayer times, Quran, and Islamic resources.',
  home_kicker: 'ASSALAMU ALAIKUM',
  home_title: 'Ajmer Garib Nawaz',
  home_subtitle: 'Dates may vary by 1 day depending on moon sighting.',
  home_upcoming_urs: 'Upcoming Urs',
  home_ajmer_shareef: 'Ajmer Shareef',
  home_explore_menu: 'Explore Menu',
  home_daily_picks: 'Daily Picks',
  home_name_of_day: 'NAME OF THE DAY',
  home_dua_of_day: 'DUA OF THE DAY',
  home_quote_of_day: 'QUOTE OF THE DAY',
  home_rate_title: 'Rate This App',
  home_rate_text: 'Support MyGNI by rating the app on the store.',
  menu_name_of_allah: '99 Name of Allah',
  menu_islamic_dua: 'Islamic Dua',
  menu_islamic_calendar: 'Islamic Calendar',
  menu_six_kalima: 'Six Kalima',
  menu_namaz_rakat: 'Namaz Rakat',
  menu_islamic_quotes: 'Islamic Quotes',
  menu_quran: 'Quran',
  menu_qibla_finder: 'Qibla Finder',
  menu_hadish: 'Hadish',
  menu_tasbih_counter: 'Tasbih Counter',
  menu_zakat_calculator: 'Zakat Calculator',
  menu_must_visit_place: 'Must Visit Place',
  menu_populer_hotels: 'Populer Hotels',
  menu_hajj_umrah_guide: 'Hajj & Umrah Guide',
  menu_nearby_places: 'Nearby Places',
  namaz_kicker: 'NAMAZ GUIDE',
  namaz_title: 'Namaz Rakat',
  namaz_subtitle:
    'View daily prayers and Jumu’ah with their sunnah, fard, nafl, and witr rakats.',
  namaz_sunnah: 'Sunnah',
  namaz_fard: 'Fard',
  namaz_nafl: 'Nafl',
  namaz_witr: 'Witr',
  namaz_total: 'Total',
  common_translation: 'Translation',
  common_english: 'English',
  screen_allah_kicker: 'ASMA UL HUSNA',
  screen_allah_title: '99 Names of Allah',
  screen_allah_subtitle:
    'Read the Arabic name, English transliteration, and meaning.',
  screen_dua_kicker: 'DUA COLLECTION',
  screen_dua_title: 'Islamic Dua',
  screen_dua_subtitle:
    'Read each dua in Arabic, English transliteration, and meaning.',
  screen_kalima_kicker: 'KALIMA COLLECTION',
  screen_kalima_title: 'Six Kalima',
  screen_kalima_subtitle:
    'Read each kalima in Arabic, English transliteration, and translation.',
  screen_quotes_kicker: 'REFLECTIONS',
  screen_quotes_title: 'Islamic Quotes',
  screen_quotes_subtitle:
    'Read inspiring quotes from the Quran and sayings of the Prophet.',
  screen_hadith_kicker: 'HADITH COLLECTION',
  screen_hadith_title: 'Islamic Hadish',
  screen_hadith_subtitle: 'Read selected hadith with their source references.',
  screen_hajj_kicker: 'PILGRIMAGE GUIDE',
  screen_hajj_title: 'Hajj & Umrah Guide',
  screen_hajj_subtitle:
    'Follow the steps clearly with separate guides for Hajj and Umrah.',
  screen_hajj_tab_hajj: 'Hajj',
  screen_hajj_tab_umrah: 'Umrah',
  screen_qibla_kicker: 'QIBLA DIRECTION',
  screen_qibla_title: 'Qibla Finder',
  screen_qibla_subtitle:
    'Direction is calculated from the current default location in the app.',
  screen_qibla_bearing: 'Qibla Bearing',
  screen_qibla_hint: 'Clockwise from North toward Makkah',
  screen_qibla_location: 'Current default location',
  screen_qibla_how: 'How to use',
  screen_qibla_how_text:
    'Face North first, then turn clockwise until you align near the shown degree. This helps you face the Kaaba for prayer.',
  screen_tasbih_kicker: 'DHIKR TRACKER',
  screen_tasbih_title: 'Tasbih Counter',
  screen_tasbih_subtitle:
    'Tap the counter to increase your dhikr count and reset anytime.',
  screen_tasbih_tap: 'Tap to Count',
  screen_tasbih_target: 'Target',
  screen_tasbih_remaining: 'Remaining',
  screen_tasbih_add_one: 'Add One',
  screen_tasbih_reset: 'Reset',
  screen_prayer_settings_kicker: 'PRAYER PREFERENCES',
  screen_prayer_settings_title: 'Prayer Settings',
  screen_prayer_settings_subtitle:
    'Configure madhab, calculation method, high latitude rule, and manual adjustments.',
  screen_prayer_settings_madhab: 'Madhab',
  screen_prayer_settings_method: 'Calculation Method',
  screen_prayer_settings_rule: 'High Latitude Rule',
  screen_prayer_settings_fajr: 'Fajr Adjustment',
  screen_prayer_settings_isha: 'Isha Adjustment',
  screen_prayer_settings_summary: 'Current Summary',
  screen_prayer_settings_method_short: 'Method',
  screen_prayer_settings_rule_short: 'Rule',
  screen_prayer_settings_min: 'min',
  screen_zakat_kicker: 'ZAKAT',
  screen_zakat_title: 'Zakat Calculator',
  screen_zakat_subtitle:
    'Enter your zakatable assets and short-term debts to estimate 2.5% zakat with a full breakdown.',
  screen_zakat_note: 'Important Note',
  screen_zakat_note_text:
    "This is an estimate. Nisab values for gold and silver are not fetched automatically, so enter today's market value yourself and confirm with a scholar when needed.",
  screen_zakat_enter: 'Enter Amounts',
  screen_zakat_details: 'Calculation Details',
  screen_zakat_cash_balance: 'Cash & Bank Balance',
  screen_zakat_cash_hint: 'Money in hand, savings, wallet',
  screen_zakat_gold_value: 'Gold Value',
  screen_zakat_gold_hint: 'Current value of zakatable gold',
  screen_zakat_silver_value: 'Silver Value',
  screen_zakat_silver_hint: 'Current value of zakatable silver',
  screen_zakat_business_assets: 'Business Assets',
  screen_zakat_business_hint: 'Stock, trade goods, business cash',
  screen_zakat_investments: 'Investments',
  screen_zakat_investments_hint: 'Zakatable shares or receivables',
  screen_zakat_debts: 'Immediate Debts',
  screen_zakat_debts_hint: 'Short-term payable debts only',
  screen_zakat_cash_bank: 'Cash & Bank',
  screen_zakat_total_assets: 'Total Assets',
  screen_zakat_minus_debts: 'Minus Debts',
  screen_zakat_net_amount: 'Net Zakatable Amount',
  screen_zakat_due: 'Zakat Due (2.5%)',
  screen_zakat_due_text:
    'Zakat is calculated as 2.5% of the net zakatable amount.',
  screen_zakat_due_empty: 'Add your amounts above to calculate your zakat.',
  screen_quran_kicker: 'BISMILLAH',
  screen_quran_title: 'Quran - All Surah',
  screen_quran_subtitle: 'Tap any Surah to view all Ayat',
  screen_quran_detail_kicker: 'SURAH DETAILS',
  screen_quran_ayat: 'Ayat',
  screen_quran_search_placeholder: 'Search surah by name, translation, or number',
  screen_quran_search_empty_title: 'No surah found',
  screen_quran_search_empty_text:
    'Try a different surah name, translation, or surah number.',
  screen_deen_ai_kicker: 'GUIDED DISCOVERY',
  screen_deen_ai_title: 'Deen AI',
  screen_deen_ai_subtitle:
    'Ask about Islamic topics and get Quran-based matches with free reference results.',
  screen_calendar_kicker: 'HIJRI VIEW',
  screen_calendar_title: 'Islamic Calendar',
  screen_calendar_today: 'Today',
  screen_calendar_english_date: 'English date',
  screen_calendar_monthly: 'Monthly Calendar',
  screen_calendar_approx: 'Approximate Hijri view',
  screen_calendar_current_date: 'Current Islamic Date',
  screen_calendar_festivals: 'Islamic Festivals',
  screen_calendar_observances: 'Common observances',
  screen_calendar_next: 'Next',
  screen_places_kicker: 'AJMER GUIDE',
  screen_places_title: 'Must Visit Place',
  screen_places_subtitle:
    'Important religious and historic places to visit in Ajmer.',
  screen_hotels_kicker: 'AJMER STAY',
  screen_hotels_title: 'Populer Hotels',
  screen_hotels_subtitle:
    'Popular hotel options near Ajmer Dargah for visitors and pilgrims.',
  screen_prayer_kicker: 'SALAH TRACKER',
  screen_prayer_title: 'Prayer Times',
  screen_prayer_next: 'Next Prayer',
  screen_prayer_live: 'Live',
  screen_prayer_time_remaining: 'Time Remaining',
  screen_prayer_previous_day: 'Previous Day',
  screen_prayer_next_day: 'Next Day',
  screen_prayer_clear_all: 'Clear All',
  screen_prayer_next_badge: 'NEXT',
  screen_prayer_alert_on: 'Alert On',
  screen_prayer_set_alert: 'Set Alert',
  screen_prayer_permission_needed: 'Permission needed',
  screen_prayer_permission_text:
    'Please allow notifications to receive prayer alerts.',
  screen_prayer_notifications_not_enabled: 'Notifications are not enabled yet.',
  screen_prayer_alerts_cleared: 'Prayer alerts cleared.',
  screen_prayer_disable_title: 'Prayer notifications disabled',
  screen_prayer_disable_text: 'All scheduled prayer alerts were removed.',
  screen_prayer_unable_schedule: 'Unable to schedule notifications',
  screen_prayer_unable_cancel: 'Unable to cancel notifications',
  screen_intro_welcome_title: 'Prayer Time',
  screen_intro_welcome_text:
    'Check accurate daily prayer times and stay connected to every salah on time.',
  screen_intro_learn_title: 'Quran',
  screen_intro_learn_text:
    'Read the Quran with a simple, focused experience designed for daily reflection.',
  screen_intro_consistent_title: 'Deen AI',
  screen_intro_consistent_text:
    'Ask Deen AI for quick Islamic guidance, learning support, and helpful answers anytime.',
  screen_intro_next: 'Next',
  screen_intro_get_started: 'Get Started',
} as const;

export type TranslationKey = keyof typeof english;
type TranslationMap = Record<TranslationKey, string>;

const translations: Record<LanguageCode, TranslationMap> = {
  en: english,
  zh: {
    ...english,
    common_back: '< 返回',
    common_active: '当前',
    common_light: '浅色',
    common_dark: '深色',
    common_system: '跟随系统',
    tabs_home: '首页',
    tabs_prayer_time: '礼拜时间',
    tabs_quran: '古兰经',
    tabs_info: '信息',
    info_title: '信息与设置',
    info_theme: '主题',
    info_language: '语言',
    info_choose_language: '选择语言',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: '功能菜单',
    home_daily_picks: '每日推荐',
    menu_name_of_allah: '真主 99 尊名',
    menu_islamic_dua: '伊斯兰祈祷',
    menu_islamic_calendar: '伊斯兰历',
    menu_six_kalima: '六段信词',
    menu_namaz_rakat: '礼拜拜数',
    menu_islamic_quotes: '伊斯兰语录',
    menu_qibla_finder: '朝向查找',
    menu_hadish: '圣训',
    menu_tasbih_counter: '念珠计数',
    menu_zakat_calculator: '天课计算器',
    menu_must_visit_place: '必去地点',
    menu_populer_hotels: '热门酒店',
    menu_hajj_umrah_guide: '朝觐与副朝指南',
    namaz_title: '礼拜拜数',
    namaz_sunnah: '圣行',
    namaz_fard: '主命',
    namaz_nafl: '自愿',
    namaz_witr: '维特尔',
  },
  es: {
    ...english,
    common_back: '< Atrás',
    common_active: 'Activo',
    common_light: 'Claro',
    common_dark: 'Oscuro',
    common_system: 'Sistema',
    tabs_home: 'Inicio',
    tabs_prayer_time: 'Horario de oración',
    tabs_quran: 'Corán',
    info_title: 'Información y ajustes',
    info_theme: 'Tema',
    info_language: 'Idioma',
    info_choose_language: 'Elegir idioma',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Menú',
    home_daily_picks: 'Selecciones del día',
    menu_name_of_allah: '99 nombres de Alá',
    menu_islamic_dua: 'Dua islámica',
    menu_islamic_calendar: 'Calendario islámico',
    menu_islamic_quotes: 'Frases islámicas',
    menu_qibla_finder: 'Buscador de qibla',
    menu_hadish: 'Hadiz',
    menu_tasbih_counter: 'Contador tasbih',
    menu_zakat_calculator: 'Calculadora de zakat',
    menu_must_visit_place: 'Lugar imperdible',
    menu_populer_hotels: 'Hoteles populares',
    menu_hajj_umrah_guide: 'Guía de Hajj y Umrah',
  },
  ar: {
    ...english,
    common_back: '< رجوع',
    common_active: 'النشط',
    common_light: 'فاتح',
    common_dark: 'داكن',
    common_system: 'النظام',
    tabs_home: 'الرئيسية',
    tabs_prayer_time: 'مواقيت الصلاة',
    tabs_quran: 'القرآن',
    tabs_info: 'المعلومات',
    info_title: 'المعلومات والإعدادات',
    info_theme: 'المظهر',
    info_language: 'اللغة',
    info_choose_language: 'اختر اللغة',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'قائمة الاستكشاف',
    home_daily_picks: 'اختيارات اليوم',
    menu_name_of_allah: 'أسماء الله الحسنى 99',
    menu_islamic_dua: 'الدعاء الإسلامي',
    menu_islamic_calendar: 'التقويم الإسلامي',
    menu_six_kalima: 'الكلمات الست',
    menu_namaz_rakat: 'ركعات الصلاة',
    menu_islamic_quotes: 'اقتباسات إسلامية',
    menu_qibla_finder: 'تحديد القبلة',
    menu_hadish: 'الحديث',
    menu_tasbih_counter: 'عداد التسبيح',
    menu_zakat_calculator: 'حاسبة الزكاة',
    menu_must_visit_place: 'أماكن يجب زيارتها',
    menu_populer_hotels: 'فنادق مشهورة',
    menu_hajj_umrah_guide: 'دليل الحج والعمرة',
    namaz_title: 'ركعات الصلاة',
    namaz_sunnah: 'سنة',
    namaz_fard: 'فرض',
    namaz_nafl: 'نفل',
    namaz_witr: 'وتر',
  },
  hi: {
    ...english,
    common_back: '< वापस',
    common_active: 'सक्रिय',
    common_light: 'लाइट',
    common_dark: 'डार्क',
    common_system: 'सिस्टम',
    tabs_home: 'होम',
    tabs_prayer_time: 'नमाज़ समय',
    tabs_quran: 'कुरआन',
    tabs_info: 'जानकारी',
    info_title: 'जानकारी और सेटिंग्स',
    info_theme: 'थीम',
    info_language: 'भाषा',
    info_choose_language: 'भाषा चुनें',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'एक्सप्लोर मेनू',
    home_daily_picks: 'आज की पसंद',
    menu_name_of_allah: 'अल्लाह के 99 नाम',
    menu_islamic_dua: 'इस्लामिक दुआ',
    menu_islamic_calendar: 'इस्लामिक कैलेंडर',
    menu_six_kalima: 'छह कलिमा',
    menu_namaz_rakat: 'नमाज़ रकात',
    menu_islamic_quotes: 'इस्लामिक कोट्स',
    menu_qibla_finder: 'किबला फाइंडर',
    menu_hadish: 'हदीस',
    menu_tasbih_counter: 'तस्बीह काउंटर',
    menu_zakat_calculator: 'ज़कात कैलकुलेटर',
    menu_must_visit_place: 'जरूर घूमने की जगह',
    menu_populer_hotels: 'लोकप्रिय होटल',
    menu_hajj_umrah_guide: 'हज और उमराह गाइड',
    namaz_title: 'नमाज़ रकात',
    namaz_sunnah: 'सुन्नत',
    namaz_fard: 'फ़र्ज़',
    namaz_nafl: 'नफ़्ल',
    namaz_witr: 'वितर',
  },
  fr: {
    ...english,
    common_back: '< Retour',
    common_light: 'Clair',
    common_dark: 'Sombre',
    common_system: 'Système',
    tabs_home: 'Accueil',
    tabs_prayer_time: 'Heures de prière',
    tabs_quran: 'Coran',
    tabs_info: 'Infos',
    info_title: 'Infos et réglages',
    info_theme: 'Thème',
    info_language: 'Langue',
    info_choose_language: 'Choisir la langue',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Menu',
    home_daily_picks: 'Choix du jour',
    menu_name_of_allah: '99 noms d’Allah',
    menu_islamic_dua: 'Doua islamique',
    menu_islamic_calendar: 'Calendrier islamique',
    menu_islamic_quotes: 'Citations islamiques',
    menu_quran: 'Coran',
    menu_hadish: 'Hadith',
    menu_tasbih_counter: 'Compteur de tasbih',
    menu_zakat_calculator: 'Calculateur de zakat',
    menu_must_visit_place: 'Lieu à visiter',
    menu_populer_hotels: 'Hôtels populaires',
    menu_hajj_umrah_guide: 'Guide du Hajj et de la Omra',
  },
  ru: {
    ...english,
    common_back: '< Назад',
    common_light: 'Светлая',
    common_dark: 'Тёмная',
    common_system: 'Система',
    tabs_home: 'Главная',
    tabs_prayer_time: 'Время намаза',
    tabs_quran: 'Коран',
    info_title: 'Инфо и настройки',
    info_theme: 'Тема',
    info_language: 'Язык',
    info_choose_language: 'Выбрать язык',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Меню',
    home_daily_picks: 'Выбор дня',
    menu_name_of_allah: '99 имен Аллаха',
    menu_islamic_dua: 'Исламская дуа',
    menu_islamic_calendar: 'Исламский календарь',
    menu_six_kalima: 'Шесть калима',
    menu_namaz_rakat: 'Ракааты намаза',
    menu_islamic_quotes: 'Исламские цитаты',
    menu_qibla_finder: 'Поиск киблы',
    menu_hadish: 'Хадис',
    menu_tasbih_counter: 'Счётчик тасбиха',
    menu_zakat_calculator: 'Калькулятор закята',
    menu_must_visit_place: 'Обязательное место',
    menu_populer_hotels: 'Популярные отели',
    menu_hajj_umrah_guide: 'Гид по хаджу и умре',
  },
  pt: {
    ...english,
    common_back: '< Voltar',
    tabs_home: 'Início',
    tabs_prayer_time: 'Horário de oração',
    tabs_quran: 'Alcorão',
    info_title: 'Info e configurações',
    info_theme: 'Tema',
    info_language: 'Idioma',
    info_choose_language: 'Escolher idioma',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Menu',
    home_daily_picks: 'Escolhas do dia',
    menu_name_of_allah: '99 nomes de Allah',
    menu_islamic_dua: 'Dua islâmica',
    menu_islamic_calendar: 'Calendário islâmico',
    menu_islamic_quotes: 'Citações islâmicas',
    menu_qibla_finder: 'Localizador de qibla',
    menu_hadish: 'Hadith',
    menu_tasbih_counter: 'Contador de tasbih',
    menu_zakat_calculator: 'Calculadora de zakat',
    menu_must_visit_place: 'Lugar para visitar',
    menu_populer_hotels: 'Hotéis populares',
    menu_hajj_umrah_guide: 'Guia de Hajj e Umrah',
  },
  bn: {
    ...english,
    common_back: '< ফিরে যান',
    tabs_home: 'হোম',
    tabs_prayer_time: 'নামাজের সময়',
    tabs_quran: 'কুরআন',
    tabs_info: 'তথ্য',
    info_title: 'তথ্য ও সেটিংস',
    info_theme: 'থিম',
    info_language: 'ভাষা',
    info_choose_language: 'ভাষা নির্বাচন করুন',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'এক্সপ্লোর মেনু',
    home_daily_picks: 'দৈনিক পছন্দ',
    menu_name_of_allah: 'আল্লাহর ৯৯ নাম',
    menu_islamic_dua: 'ইসলামিক দোয়া',
    menu_islamic_calendar: 'ইসলামিক ক্যালেন্ডার',
    menu_six_kalima: 'ছয় কালিমা',
    menu_namaz_rakat: 'নামাজ রাকাত',
    menu_islamic_quotes: 'ইসলামিক উক্তি',
    menu_hadish: 'হাদিস',
    menu_tasbih_counter: 'তাসবিহ কাউন্টার',
    menu_zakat_calculator: 'যাকাত ক্যালকুলেটর',
    menu_must_visit_place: 'দেখতেই হবে এমন স্থান',
    menu_populer_hotels: 'জনপ্রিয় হোটেল',
    menu_hajj_umrah_guide: 'হজ ও উমরাহ গাইড',
  },
  id: {
    ...english,
    common_back: '< Kembali',
    tabs_home: 'Beranda',
    tabs_prayer_time: 'Waktu salat',
    info_title: 'Info & pengaturan',
    info_theme: 'Tema',
    info_language: 'Bahasa',
    info_choose_language: 'Pilih bahasa',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Menu eksplorasi',
    home_daily_picks: 'Pilihan harian',
    menu_name_of_allah: '99 Nama Allah',
    menu_islamic_dua: 'Doa Islami',
    menu_islamic_calendar: 'Kalender Islami',
    menu_islamic_quotes: 'Kutipan Islami',
    menu_qibla_finder: 'Pencari kiblat',
    menu_tasbih_counter: 'Penghitung tasbih',
    menu_zakat_calculator: 'Kalkulator zakat',
    menu_must_visit_place: 'Tempat wajib dikunjungi',
    menu_populer_hotels: 'Hotel populer',
    menu_hajj_umrah_guide: 'Panduan Haji & Umrah',
  },
  tr: {
    ...english,
    common_back: '< Geri',
    tabs_home: 'Ana sayfa',
    tabs_prayer_time: 'Namaz vakti',
    tabs_quran: 'Kuran',
    tabs_info: 'Bilgi',
    info_title: 'Bilgi ve ayarlar',
    info_theme: 'Tema',
    info_language: 'Dil',
    info_choose_language: 'Dil seçin',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Menü',
    home_daily_picks: 'Günün seçimleri',
    menu_name_of_allah: 'Allah’ın 99 ismi',
    menu_islamic_dua: 'İslami dua',
    menu_islamic_calendar: 'İslami takvim',
    menu_namaz_rakat: 'Namaz rekatı',
    menu_islamic_quotes: 'İslami sözler',
    menu_qibla_finder: 'Kıble bulucu',
    menu_hadish: 'Hadis',
    menu_tasbih_counter: 'Tesbih sayacı',
    menu_zakat_calculator: 'Zekat hesaplayıcı',
    menu_must_visit_place: 'Görülmesi gereken yer',
    menu_populer_hotels: 'Popüler oteller',
    menu_hajj_umrah_guide: 'Hac ve Umre rehberi',
  },
  de: {
    ...english,
    common_back: '< Zurück',
    tabs_home: 'Start',
    tabs_prayer_time: 'Gebetszeiten',
    tabs_quran: 'Koran',
    info_title: 'Info & Einstellungen',
    info_theme: 'Thema',
    info_language: 'Sprache',
    info_choose_language: 'Sprache wählen',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'Menü',
    home_daily_picks: 'Tagesauswahl',
    menu_name_of_allah: '99 Namen Allahs',
    menu_islamic_dua: 'Islamische Dua',
    menu_islamic_calendar: 'Islamischer Kalender',
    menu_islamic_quotes: 'Islamische Zitate',
    menu_qibla_finder: 'Qibla-Finder',
    menu_hadish: 'Hadith',
    menu_tasbih_counter: 'Tasbih-Zähler',
    menu_zakat_calculator: 'Zakat-Rechner',
    menu_must_visit_place: 'Sehenswerter Ort',
    menu_populer_hotels: 'Beliebte Hotels',
    menu_hajj_umrah_guide: 'Hajj- und Umrah-Leitfaden',
  },
  ja: {
    ...english,
    common_back: '< 戻る',
    common_light: 'ライト',
    common_dark: 'ダーク',
    common_system: 'システム',
    tabs_home: 'ホーム',
    tabs_prayer_time: '礼拝時間',
    tabs_quran: 'クルアーン',
    tabs_info: '情報',
    info_title: '情報と設定',
    info_theme: 'テーマ',
    info_language: '言語',
    info_choose_language: '言語を選択',
    home_title: 'Ajmer Garib Nawaz',
    home_explore_menu: 'メニュー',
    home_daily_picks: '今日のおすすめ',
    menu_name_of_allah: 'アッラーの99の御名',
    menu_islamic_dua: 'イスラムのドゥアー',
    menu_islamic_calendar: 'イスラム暦',
    menu_namaz_rakat: 'ナマズのラカート',
    menu_islamic_quotes: 'イスラムの言葉',
    menu_qibla_finder: 'キブラ検索',
    menu_tasbih_counter: 'タスビーフカウンター',
    menu_zakat_calculator: 'ザカート計算機',
    menu_must_visit_place: '必見の場所',
    menu_populer_hotels: '人気ホテル',
    menu_hajj_umrah_guide: 'ハッジとウムラのガイド',
  },
};

type LocalizationContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: TranslationKey) => string;
};

const LocalizationContext = createContext<LocalizationContextValue | null>(null);

export function LocalizationProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: TranslationKey) => translations[language][key] ?? english[key],
    }),
    [language],
  );

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useLocalization() {
  const context = useContext(LocalizationContext);

  if (!context) {
    throw new Error('useLocalization must be used inside LocalizationProvider');
  }

  return context;
}
